### ISSUE TITLE
FR: support negative values

### ISSUE THREAD

**Issue by el-schneider** [azat-io/postcss-responsive#1]
Hi @azat-io,

great plugin! I'm a bit suprised not many people seem to know of it. It would be nice if the plugin eventually could support negative values. A common use-case would be: 
```css 
letter-spacing: responsive(-1px, -2px);
```
Cheers

**Comment by azat-io** [comment]
Thanks for your feedback. I'll try to do this soon

**Comment by azat-io** [comment]
Released in [v0.2.0](https://github.com/azat-io/postcss-responsive/blob/main/changelog.md#020-2023-01-16) 🚀
